import type { Lesson } from "../../types";

export const accretion: Lesson = {
	id: "accretion",
	title: "Accretion onto Compact Objects",
	chapterId: "compact-objects",
	content: `## Accretion onto Compact Objects

When matter falls onto a compact object — a white dwarf, neutron star, or black hole — gravitational potential energy is released as radiation. Accretion is one of the most powerful energy sources in the universe.

### Accretion Luminosity

The luminosity generated by mass falling from infinity onto a compact object of mass $M$ and radius $R$ at a mass accretion rate $\\dot{M}$ (kg/s) is:

$$L_{\\text{acc}} = \\frac{G M \\dot{M}}{R}$$

### Radiative Efficiency

The efficiency $\\eta$ compares the radiated energy to the rest-mass energy of the accreted material:

$$\\eta = \\frac{G M}{R c^2}$$

so that $L_{\\text{acc}} = \\eta \\dot{M} c^2$.

| Object | $R$ | $\\eta$ |
|--------|-----|---------|
| White dwarf | $\\sim 10^7$ m | $\\sim 0.02\\%$ |
| Neutron star | $\\sim 10$ km | $\\sim 20\\%$ |
| Black hole (ISCO) | $6 G M / c^2$ | $\\sim 5.7\\%$ |

For a neutron star with $M = 1.4\\,M_\\odot$ and $R = 10$ km:

$$\\eta_{\\text{NS}} = \\frac{G \\times 1.4 M_\\odot}{10^4 \\text{ m} \\times c^2} \\approx 0.207$$

For a Schwarzschild black hole, the innermost stable circular orbit (ISCO) is at $R_{\\text{ISCO}} = 6 G M / c^2 = 3 r_s$, giving $\\eta = 1/6 \\approx 16.7\\%$.

### Your Task

Implement three functions. All constants must be defined **inside** each function.

- \`accretion_luminosity_W(M_kg, Mdot_kg_s, R_m)\` — returns $L_{\\text{acc}} = G M \\dot{M} / R$ in watts
- \`accretion_efficiency(M_kg, R_m)\` — returns $\\eta = G M / (R c^2)$ (dimensionless)
- \`mdot_from_luminosity(L_W, M_kg, R_m)\` — returns $\\dot{M} = L R / (G M)$ in kg/s

Use $G = 6.674 \\times 10^{-11}$ N m² kg⁻² and $c = 2.998 \\times 10^8$ m/s.`,

	starterCode: `import math

def accretion_luminosity_W(M_kg, Mdot_kg_s, R_m):
    G = 6.674e-11
    # TODO: return G * M_kg * Mdot_kg_s / R_m
    pass

def accretion_efficiency(M_kg, R_m):
    G = 6.674e-11
    c = 2.998e8
    # TODO: return G * M_kg / (R_m * c**2)
    pass

def mdot_from_luminosity(L_W, M_kg, R_m):
    G = 6.674e-11
    # TODO: return L_W * R_m / (G * M_kg)
    pass

M_ns = 1.4 * 1.989e30
R_ns = 1e4
print(round(accretion_efficiency(M_ns, R_ns), 4))
`,

	solution: `import math

def accretion_luminosity_W(M_kg, Mdot_kg_s, R_m):
    G = 6.674e-11
    return G * M_kg * Mdot_kg_s / R_m

def accretion_efficiency(M_kg, R_m):
    G = 6.674e-11
    c = 2.998e8
    return G * M_kg / (R_m * c**2)

def mdot_from_luminosity(L_W, M_kg, R_m):
    G = 6.674e-11
    return L_W * R_m / (G * M_kg)

M_ns = 1.4 * 1.989e30
R_ns = 1e4
print(round(accretion_efficiency(M_ns, R_ns), 4))
`,

	tests: [
		{
			name: "Neutron star efficiency ≈ 0.2068 (20.7%)",
			code: `{{FUNC}}
print(round(accretion_efficiency(1.4 * 1.989e30, 1e4), 4))`,
			expected: "0.2068\n",
		},
		{
			name: "Neutron star accretion luminosity (mdot=1e10 kg/s) ≈ 1.8584e26 W",
			code: `{{FUNC}}
L = accretion_luminosity_W(1.4 * 1.989e30, 1e10, 1e4)
print(round(L / 1e26, 4))`,
			expected: "1.8584\n",
		},
		{
			name: "Black hole ISCO efficiency ≈ 1/6 ≈ 0.1667",
			code: `{{FUNC}}
G = 6.674e-11
c = 2.998e8
M_bh = 10 * 1.989e30
R_isco = 6 * G * M_bh / c**2
print(round(accretion_efficiency(M_bh, R_isco), 4))`,
			expected: "0.1667\n",
		},
		{
			name: "mdot_from_luminosity inverts accretion_luminosity_W",
			code: `{{FUNC}}
M_ns = 1.4 * 1.989e30
R_ns = 1e4
L = accretion_luminosity_W(M_ns, 1e9, R_ns)
mdot = mdot_from_luminosity(L, M_ns, R_ns)
print(round(mdot / 1e9, 6))`,
			expected: "1.0\n",
		},
	],
};
