import type { Lesson } from "../../types";

export const ideals: Lesson = {
	id: "ideals",
	title: "Ideals",
	chapterId: "rings",
	content: `## Ideals

An **ideal** $I$ of a ring $R$ is a subset that is:
1. A subgroup of $(R, +)$
2. **Absorbing** under multiplication: for all $r \\in R$ and $a \\in I$, both $ra \\in I$ and $ar \\in I$

Ideals are to rings what normal subgroups are to groups — they let us form quotient structures.

### Ideals in $\\mathbb{Z}_n$

In $\\mathbb{Z}_n$, every ideal is **principal** — generated by a single element. The ideal generated by $a$ is:

$$\\langle a \\rangle = \\{0, a, 2a, 3a, \\ldots\\} \\pmod{n}$$

which equals $\\{ka \\bmod n : k = 0, 1, \\ldots\\}$.

### Example: Ideals of $\\mathbb{Z}_6$

- $\\langle 0 \\rangle = \\{0\\}$
- $\\langle 1 \\rangle = \\{0, 1, 2, 3, 4, 5\\} = \\mathbb{Z}_6$
- $\\langle 2 \\rangle = \\{0, 2, 4\\}$
- $\\langle 3 \\rangle = \\{0, 3\\}$

Note: $\\langle 4 \\rangle = \\{0, 4, 2\\} = \\langle 2 \\rangle$ and $\\langle 5 \\rangle = \\langle 1 \\rangle$.

### Maximal and Prime Ideals

- An ideal $I \\neq R$ is **maximal** if no ideal lies strictly between $I$ and $R$
- An ideal $I$ is **prime** if $ab \\in I$ implies $a \\in I$ or $b \\in I$

In $\\mathbb{Z}_n$, $\\langle d \\rangle$ is a prime ideal if and only if $d$ is prime (or $d = 0$ when $n$ is prime).

### Your Task

Implement \`principal_ideal(a, n)\` returning the sorted elements of $\\langle a \\rangle$ in $\\mathbb{Z}_n$, \`all_ideals(n)\` returning all distinct ideals (sorted by size then lex), and \`is_prime_ideal(ideal, n)\` checking the prime ideal condition.`,

	starterCode: `def principal_ideal(a, n):
    # Return sorted elements of <a> in Z_n
    pass

def all_ideals(n):
    # Return all distinct ideals of Z_n
    pass

def is_prime_ideal(ideal, n):
    # Check if ideal is a prime ideal in Z_n
    pass

print(principal_ideal(2, 6))
print(principal_ideal(3, 6))
ideals = all_ideals(6)
for i in ideals:
    print(i, is_prime_ideal(i, 6))
`,

	solution: `def principal_ideal(a, n):
    ideal = set()
    for k in range(n):
        ideal.add((k * a) % n)
    return sorted(ideal)

def all_ideals(n):
    seen = set()
    result = []
    for a in range(n):
        ideal = tuple(principal_ideal(a, n))
        if ideal not in seen:
            seen.add(ideal)
            result.append(list(ideal))
    result.sort(key=lambda x: (len(x), x))
    return result

def is_prime_ideal(ideal, n):
    ideal_set = set(ideal)
    if ideal_set == set(range(n)):
        return False
    for a in range(n):
        for b in range(n):
            if (a * b) % n in ideal_set:
                if a not in ideal_set and b not in ideal_set:
                    return False
    return True

print(principal_ideal(2, 6))
print(principal_ideal(3, 6))
ideals = all_ideals(6)
for i in ideals:
    print(i, is_prime_ideal(i, 6))
`,

	tests: [
		{
			name: "Ideals of Z_6 with prime ideal check",
			expected:
				"[0, 2, 4]\n[0, 3]\n[0] False\n[0, 3] True\n[0, 2, 4] True\n[0, 1, 2, 3, 4, 5] False\n",
		},
		{
			name: "Principal ideal <3> in Z_9",
			code: `{{FUNC}}
print(principal_ideal(3, 9))`,
			expected: "[0, 3, 6]\n",
		},
		{
			name: "Number of ideals of Z_12",
			code: `{{FUNC}}
print(len(all_ideals(12)))`,
			expected: "6\n",
		},
	],
};
