#!/usr/bin/env bash
set -euo pipefail

# Build Aiwnios HolyC compiler to WebAssembly using Emscripten.
#
# This script applies headless-mode patches to Aiwnios, embeds the pre-built
# HolyC Runtime (HCRT2.BIN), and compiles everything to a single self-contained
# JS+WASM file suitable for in-browser execution.
#
# Requirements:
#   - git
#   - emcc / emcmake / emmake  (Emscripten SDK; source emsdk_env.sh first)
#   - cmake
#   - patch
#
# Usage:
#   source /path/to/emsdk/emsdk_env.sh
#   ./scripts/build-holyc-wasm.sh
#
# Output:
#   public/holyc/aiwnios.js   (single-file: JS + WASM + HCRT2.BIN, ~6.5 MB)
#
# How HCRT2.BIN is obtained:
#   HCRT2.BIN is the pre-compiled HolyC Runtime binary.  It is checked in at
#   scripts/holyc-wasm/HCRT2.BIN (generated by running `aiwnios -b` on the
#   native Aiwnios binary).  To regenerate it from source you would need a
#   working native Aiwnios build (x86_64 or arm64 Linux/macOS with SDL2), then:
#     cmake -B native-build && make -C native-build
#     ./aiwnios -b   # produces HCRT2.BIN and HCRT2.DBG.Z in the repo root
#
# Headless-mode patch (scripts/holyc-wasm/aiwnios-headless.patch):
#   Adds holyc_set_file() / holyc_is_done() / holyc_step() WASM exports and
#   bypasses SDL when running scripts non-interactively.  This is required for
#   the in-browser lesson runner to execute user code without a graphical OS.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$PROJECT_DIR/public/holyc"
ASSETS_DIR="$SCRIPT_DIR/holyc-wasm"
TMP_DIR="/tmp/aiwnios-build-$$"

echo "==> Checking dependencies..."
command -v git   >/dev/null || { echo "ERROR: git not found"; exit 1; }
command -v emcc  >/dev/null || { echo "ERROR: emcc not found. Source the Emscripten SDK first: source emsdk_env.sh"; exit 1; }
command -v cmake >/dev/null || { echo "ERROR: cmake not found"; exit 1; }
command -v patch >/dev/null || { echo "ERROR: patch not found"; exit 1; }

test -f "$ASSETS_DIR/HCRT2.BIN" || { echo "ERROR: $ASSETS_DIR/HCRT2.BIN not found"; exit 1; }
test -f "$ASSETS_DIR/aiwnios-headless.patch" || { echo "ERROR: $ASSETS_DIR/aiwnios-headless.patch not found"; exit 1; }

echo "==> Cloning Aiwnios (commit pinned to tested revision)..."
git clone --depth 1 https://github.com/Aiwnios/Aiwnios "$TMP_DIR"

echo "==> Applying headless-mode patch..."
patch -d "$TMP_DIR" -p1 < "$ASSETS_DIR/aiwnios-headless.patch"

echo "==> Setting up wasmStage-minimal with pre-built HCRT2.BIN..."
mkdir -p "$TMP_DIR/wasmStage-minimal"
cp "$ASSETS_DIR/HCRT2.BIN" "$TMP_DIR/wasmStage-minimal/HCRT2.BIN"
# PersonalMenu.DD is needed by the HolyC runtime for menu configuration
cp "$TMP_DIR/wasmStage/PersonalMenu.DD" "$TMP_DIR/wasmStage-minimal/PersonalMenu.DD" 2>/dev/null || true

echo "==> Configuring with Emscripten..."
cd "$TMP_DIR"
emcmake cmake -B wasm-build \
  -DUSE_BYTECODE=on \
  -DCMAKE_BUILD_TYPE=Release

echo "==> Building..."
emmake make -C wasm-build -j"$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)"

echo "==> Copying output to $OUTPUT_DIR..."
mkdir -p "$OUTPUT_DIR"
# The patch sets SUFFIX ".js" and SINGLE_FILE=1, so output is a single .js file
cp "$TMP_DIR/aiwnios.js" "$OUTPUT_DIR/aiwnios.js"

echo "==> Cleaning up..."
rm -rf "$TMP_DIR"

echo ""
echo "Done! Files written to $OUTPUT_DIR:"
ls -lh "$OUTPUT_DIR"
echo ""
echo "To use: start the dev server with 'npm run dev' and navigate to /courses/holyc"
